# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lunar/pros/evo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lunar/pros/evo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lunar/pros/evo/CMakeFiles /Users/lunar/pros/evo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lunar/pros/evo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named evo

# Build rule for target.
evo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 evo
.PHONY : evo

# fast build rule for target.
evo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evo.dir/build.make CMakeFiles/evo.dir/build
.PHONY : evo/fast

#=============================================================================
# Target rules for targets named out

# Build rule for target.
out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 out
.PHONY : out

# fast build rule for target.
out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/build
.PHONY : out/fast

src/coroutine/io_scheduler.o: src/coroutine/io_scheduler.cpp.o
.PHONY : src/coroutine/io_scheduler.o

# target to build an object file
src/coroutine/io_scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evo.dir/build.make CMakeFiles/evo.dir/src/coroutine/io_scheduler.cpp.o
.PHONY : src/coroutine/io_scheduler.cpp.o

src/coroutine/io_scheduler.i: src/coroutine/io_scheduler.cpp.i
.PHONY : src/coroutine/io_scheduler.i

# target to preprocess a source file
src/coroutine/io_scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evo.dir/build.make CMakeFiles/evo.dir/src/coroutine/io_scheduler.cpp.i
.PHONY : src/coroutine/io_scheduler.cpp.i

src/coroutine/io_scheduler.s: src/coroutine/io_scheduler.cpp.s
.PHONY : src/coroutine/io_scheduler.s

# target to generate assembly for a file
src/coroutine/io_scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/evo.dir/build.make CMakeFiles/evo.dir/src/coroutine/io_scheduler.cpp.s
.PHONY : src/coroutine/io_scheduler.cpp.s

test/test1.o: test/test1.cpp.o
.PHONY : test/test1.o

# target to build an object file
test/test1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/test/test1.cpp.o
.PHONY : test/test1.cpp.o

test/test1.i: test/test1.cpp.i
.PHONY : test/test1.i

# target to preprocess a source file
test/test1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/test/test1.cpp.i
.PHONY : test/test1.cpp.i

test/test1.s: test/test1.cpp.s
.PHONY : test/test1.s

# target to generate assembly for a file
test/test1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/out.dir/build.make CMakeFiles/out.dir/test/test1.cpp.s
.PHONY : test/test1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... evo"
	@echo "... out"
	@echo "... src/coroutine/io_scheduler.o"
	@echo "... src/coroutine/io_scheduler.i"
	@echo "... src/coroutine/io_scheduler.s"
	@echo "... test/test1.o"
	@echo "... test/test1.i"
	@echo "... test/test1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

